"""add listener analytics

Revision ID: 08e61e99db94
Revises: 5432e2928a3a
Create Date: 2026-08-13 16:01:50.541476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e61e99db94'
down_revision: Union[str, Sequence[str], None] = '5432e2928a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listener_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('listener_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.String(length=100), nullable=False),
    sa.Column('show_id', sa.String(length=150), nullable=False),
    sa.Column('episode_id', sa.String(length=150), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listener_events_creator_episode_time', 'listener_events', ['creator_id', 'episode_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_listener_events_creator_id'), 'listener_events', ['creator_id'], unique=False)
    op.create_index(op.f('ix_listener_events_episode_id'), 'listener_events', ['episode_id'], unique=False)
    op.create_index(op.f('ix_listener_events_event_type'), 'listener_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_listener_events_id'), 'listener_events', ['id'], unique=False)
    op.create_index(op.f('ix_listener_events_listener_id'), 'listener_events', ['listener_id'], unique=False)
    op.create_index(op.f('ix_listener_events_occurred_at'), 'listener_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_listener_events_session_id'), 'listener_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_listener_events_show_id'), 'listener_events', ['show_id'], unique=False)
    op.create_table('listener_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('listener_id', sa.String(length=100), nullable=False),
    sa.Column('creator_id', sa.String(length=100), nullable=False),
    sa.Column('show_id', sa.String(length=150), nullable=False),
    sa.Column('episode_id', sa.String(length=150), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listener_sessions_creator_episode_heartbeat', 'listener_sessions', ['creator_id', 'episode_id', 'last_heartbeat'], unique=False)
    op.create_index(op.f('ix_listener_sessions_creator_id'), 'listener_sessions', ['creator_id'], unique=False)
    op.create_index(op.f('ix_listener_sessions_episode_id'), 'listener_sessions', ['episode_id'], unique=False)
    op.create_index(op.f('ix_listener_sessions_id'), 'listener_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_listener_sessions_last_heartbeat'), 'listener_sessions', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_listener_sessions_listener_id'), 'listener_sessions', ['listener_id'], unique=False)
    op.create_index(op.f('ix_listener_sessions_session_id'), 'listener_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_listener_sessions_show_id'), 'listener_sessions', ['show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listener_sessions_show_id'), table_name='listener_sessions')
    op.drop_index(op.f('ix_listener_sessions_session_id'), table_name='listener_sessions')
    op.drop_index(op.f('ix_listener_sessions_listener_id'), table_name='listener_sessions')
    op.drop_index(op.f('ix_listener_sessions_last_heartbeat'), table_name='listener_sessions')
    op.drop_index(op.f('ix_listener_sessions_id'), table_name='listener_sessions')
    op.drop_index(op.f('ix_listener_sessions_episode_id'), table_name='listener_sessions')
    op.drop_index(op.f('ix_listener_sessions_creator_id'), table_name='listener_sessions')
    op.drop_index('ix_listener_sessions_creator_episode_heartbeat', table_name='listener_sessions')
    op.drop_table('listener_sessions')
    op.drop_index(op.f('ix_listener_events_show_id'), table_name='listener_events')
    op.drop_index(op.f('ix_listener_events_session_id'), table_name='listener_events')
    op.drop_index(op.f('ix_listener_events_occurred_at'), table_name='listener_events')
    op.drop_index(op.f('ix_listener_events_listener_id'), table_name='listener_events')
    op.drop_index(op.f('ix_listener_events_id'), table_name='listener_events')
    op.drop_index(op.f('ix_listener_events_event_type'), table_name='listener_events')
    op.drop_index(op.f('ix_listener_events_episode_id'), table_name='listener_events')
    op.drop_index(op.f('ix_listener_events_creator_id'), table_name='listener_events')
    op.drop_index('ix_listener_events_creator_episode_time', table_name='listener_events')
    op.drop_table('listener_events')
    # ### end Alembic commands ###
